<?php
$modelCode = '';

function  modelOmega($model){
switch($model) {

case 'Constellation' : $modelCode =  '&models=60';
break;

case 'Constellation Day-Date' : $modelCode =  'models=1076'; 
break;

case 'Constellation Double Eagle' : $modelCode =  '&models=2440'; 
break;
case 'Constellation Ladies' : $modelCode =  '&models=61'; 
break;
case 'Constellation Petite Seconde' : $modelCode =  '&models=2575'; 
break;
case 'Constellation Men' : $modelCode =  '&models=1077'; 
break;
case 'Constellation Quadra' : $modelCode =  '&models=3070'; 
break;
case 'Constellation Quartz' : $modelCode =  '&models=1078'; 
break;
case 'De Ville' : $modelCode =  '&models=62'; 
break;
case 'De Ville Central Tourbillon' : $modelCode =  '&models=2576'; 
break;
case 'De Ville Co-Axial' : $modelCode =  '&models=38'; 
break;
case 'De Ville Hour Vision' : $modelCode =  '&models=637'; 
break;
case 'De Ville Ladymatic' : $modelCode =  '&models=635'; 
break;
case 'De Ville Prestige' : $modelCode =  '&models=636'; 
break;
case 'De Ville Tresor' : $modelCode =  '&models='; 
break;
case 'De Ville X2' : $modelCode =  '&models=2576'; 
break;
case 'Dynamic Chronograph' : $modelCode =  '&models=2489'; 
break;
case 'Flightmaster' : $modelCode =  '&models=1081'; 
break;
case 'Genève' : $modelCode =  '&models=1082'; 
break;
case 'Globemaster' : $modelCode =  '&models=1080'; 
break;
case 'Memomatic' : $modelCode =  '&models=63'; 
break;
case 'Museum' : $modelCode =  '&models=525'; 
break;
case 'Seamaster' : $modelCode =  '&models=66'; 
break;
case 'Seamaster 120 M' : $modelCode =  '&models=3067'; 
break;
case 'Seamaster 1948' : $modelCode =  '&models=3068'; 
break;
case 'Seamaster  300' : $modelCode =  '&models=376'; 
break;
case 'Seamaster  Apnea' : $modelCode =  '&models=3066'; 
break;
case 'Seamaster Aqua Terra' : $modelCode =  '&models=68'; 
break;
case 'Seamaster Bullhead' : $modelCode =  '&models=1074'; 
break;
case 'Seamaster DeVille' : $modelCode =  '&models=276'; 
break;
case 'Seamaster Diver 300 M' : $modelCode =  '&models=1073'; 
break;
case 'Seamaster Planet Ocean' : $modelCode =  '&models=65'; 
break;
case 'Seamaster Planet Ocean Chronograph' : $modelCode =  '&models=375'; 
break;
case 'Seamaster PloProf' : $modelCode =  '&models=67'; 
break;
case 'Seamaster Railmaster' : $modelCode =  '&models=69'; 
break;
case 'Speedmaster' : $modelCode =  '&models=74'; 
break;
case 'Speedmaster 57' : $modelCode =  '&models=1083'; 
break;
case 'Speedmaster Broad Arrow' : $modelCode =  '&models=242'; 
break;
case 'Speedmaster Date' : $modelCode =  '&models=277'; 
break;
case 'Speedmaster Day Date' : $modelCode =  '&models=73'; 
break;
case 'Speedmaster HB-SIA' : $modelCode =  '&models=1086'; 
break;
case 'Speedmaster Ladies Chronograph' : $modelCode =  '&models=2442'; 
break;
case 'Speedmaster Mark II' : $modelCode =  '&models=1084'; 
break;
case 'Speedmaster Mark III' : $modelCode =  '&models=3052'; 
break;
case 'Speedmaster Mark IV' : $modelCode = '&models=3053'; 
break;
case 'Speedmaster Professional Moonwatch' : $modelCode = '&models=71';
break;
case 'Speedmaster Professional Moonwatch Moonphase' : $modelCode = '&models=243'; 
break;
case 'Speedmaster Racing' : $modelCode =  '&models=1085'; 
break;
case 'Speedmaster Reduced' : $modelCode =  '&models=72'; 
break;
case 'Speedmaster Skywalker X-33' : $modelCode =  '&models=1087'; 
break;
case 'Speedmaster  Spacemaker Z-33' : $modelCode =  '&models=2441'; 
break;
case 'Speedmaster  Split-Seconds' : $modelCode =  '&models=3069'; 
break;
case 'Speedsonic' : $modelCode =  '&models=3071'; 
break;
}
return $modelCode;
}

<?php
$modelCode = '';

function  modelOmega($model){
switch($model) {

case 'Constellation' : $modelCode =  '&models=60';
break;

case 'Constellation Day-Date' : $modelCode =  'models=1076'; 
break;

case 'Constellation Double Eagle' : $modelCode =  '&models=2440'; 
break;
case 'Constellation Ladies' : $modelCode =  '&models=61'; 
break;
case 'Constellation Petite Seconde' : $modelCode =  '&models=2575'; 
break;
case 'Constellation Men' : $modelCode =  '&models=1077'; 
break;
case 'Constellation Quadra' : $modelCode =  '&models=3070'; 
break;
case 'Constellation Quartz' : $modelCode =  '&models=1078'; 
break;
case 'De Ville' : $modelCode =  '&models=62'; 
break;
case 'De Ville Central Tourbillon' : $modelCode =  '&models=2576'; 
break;
case 'De Ville Co-Axial' : $modelCode =  '&models=38'; 
break;
case 'De Ville Hour Vision' : $modelCode =  '&models=637'; 
break;
case 'De Ville Ladymatic' : $modelCode =  '&models=635'; 
break;
case 'De Ville Prestige' : $modelCode =  '&models=636'; 
break;
case 'De Ville Tresor' : $modelCode =  '&models='; 
break;
case 'De Ville X2' : $modelCode =  '&models=2576'; 
break;
case 'Dynamic Chronograph' : $modelCode =  '&models=2489'; 
break;
case 'Flightmaster' : $modelCode =  '&models=1081'; 
break;
case 'Genève' : $modelCode =  '&models=1082'; 
break;
case 'Globemaster' : $modelCode =  '&models=1080'; 
break;
case 'Memomatic' : $modelCode =  '&models=63'; 
break;
case 'Museum' : $modelCode =  '&models=525'; 
break;
case 'Seamaster' : $modelCode =  '&models=66'; 
break;
case 'Seamaster 120 M' : $modelCode =  '&models=3067'; 
break;
case 'Seamaster 1948' : $modelCode =  '&models=3068'; 
break;
case 'Seamaster  300' : $modelCode =  '&models=376'; 
break;
case 'Seamaster  Apnea' : $modelCode =  '&models=3066'; 
break;
case 'Seamaster Aqua Terra' : $modelCode =  '&models=68'; 
break;
case 'Seamaster Bullhead' : $modelCode =  '&models=1074'; 
break;
case 'Seamaster DeVille' : $modelCode =  '&models=276'; 
break;
case 'Seamaster Diver 300 M' : $modelCode =  '&models=1073'; 
break;
case 'Seamaster Planet Ocean' : $modelCode =  '&models=65'; 
break;
case 'Seamaster Planet Ocean Chronograph' : $modelCode =  '&models=375'; 
break;
case 'Seamaster PloProf' : $modelCode =  '&models=67'; 
break;
case 'Seamaster Railmaster' : $modelCode =  '&models=69'; 
break;
case 'Speedmaster' : $modelCode =  '&models=74'; 
break;
case 'Speedmaster 57' : $modelCode =  '&models=1083'; 
break;
case 'Speedmaster Broad Arrow' : $modelCode =  '&models=242'; 
break;
case 'Speedmaster Date' : $modelCode =  '&models=277'; 
break;
case 'Speedmaster Day Date' : $modelCode =  '&models=73'; 
break;
case 'Speedmaster HB-SIA' : $modelCode =  '&models=1086'; 
break;
case 'Speedmaster Ladies Chronograph' : $modelCode =  '&models=2442'; 
break;
case 'Speedmaster Mark II' : $modelCode =  '&models=1084'; 
break;
case 'Speedmaster Mark III' : $modelCode =  '&models=3052'; 
break;
case 'Speedmaster Mark IV' : $modelCode = '&models=3053'; 
break;
case 'Speedmaster Professional Moonwatch' : $modelCode = '&models=71';
break;
case 'Speedmaster Professional Moonwatch Moonphase' : $modelCode = '&models=243'; 
break;
case 'Speedmaster Racing' : $modelCode =  '&models=1085'; 
break;
case 'Speedmaster Reduced' : $modelCode =  '&models=72'; 
break;
case 'Speedmaster Skywalker X-33' : $modelCode =  '&models=1087'; 
break;
case 'Speedmaster  Spacemaker Z-33' : $modelCode =  '&models=2441'; 
break;
case 'Speedmaster  Split-Seconds' : $modelCode =  '&models=3069'; 
break;
case 'Speedsonic' : $modelCode =  '&models=3071'; 
break;
}
return $modelCode;
}


?>